---
title: "UN Report Part of Workshop"
author: "KT"
date: "2023-01-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo = FALSE}
library(tidyverse)
library(ggplot2)
library(readr)
library(knitr)
```

```{r data}
gapminder_1997 <- read_csv("un-report/gapminder_1997.csv")

```

```{r gdp_lifeexp_1997}
ggplot(data = gapminder_1997) + 
  aes(x = gdpPercap, y = lifeExp, color=continent, size=pop/1000000) +
  geom_point() +
  labs(x = "GDP Per Capita", y = "Life Expectancy",
       title= "Do people in wealthy countries live longer?", size="Population (in millions)")
```

```{r Country-stats}
# Number of countries in dataset
nCountries<-
  gapminder_1997 %>%
  select(country) %>%
  n_distinct()

#minimum GPD
minGDP <- gapminder_1997 %>%
  summarise(round(min(gdpPercap))) %>%
  pull()

maxGDP <- gapminder_1997 %>%
  summarise(round(max(gdpPercap))) %>%
  pull()
```

The number of countries in the dataset is `r nCountries`. 
The minimum GDP is `r minGDP` and the maximum GDP is `r maxGDP`

```{r table}
#Use knitr to include a table in the markdown
gapminder_1997%>%
  filter(continent=="Oceania") %>%
  kable()
```

